-- Write only the SQL statement that solves the problem and nothing else.
    
  SELECT M.NAME AS MOTHER, F.NAME as FATHER ,P1.AGE AS [AGE] 

  FROM PEOPLE M

 INNER JOIN 
 (
  SELECT MOTHERID ,FATHERID,MIN(AGE)AGE FROM PEOPLE WHERE MOTHERID IS NOT NULL AND FATHERID IS NOT NULL
  
 ) 
  P1 ON M.ID =P1.MOTHERID  
  INNER JOIN PEOPLE F ON F.ID=P1.FATHERID 